import { SAVE_SCHEMA_VERSION, type PlayerSaveV2 } from './saveSchema'

export function createDefaultSave(now = Date.now()): PlayerSaveV2 {
  return {
    schemaVersion: SAVE_SCHEMA_VERSION,
    saveRevision: 0,
    currentPP: { m: 0, e: 0 },
    runPPEarned: { m: 0, e: 0 },
    lifetimePPEarned: { m: 0, e: 0 },
    tapCount: 0,
    sessionTapCount: 0,
    critCount: 0,
    highestCPS: 0,
    highestPPS: { m: 0, e: 0 },
    generators: {},
    purchasedRunUpgrades: {},
    claimedGeneratorMilestones: {},
    flushCount: 0,
    flushPower: 0,
    royalFlushLevels: {},
    gtp: 0,
    inventoryChests: { regular: 0, silver: 0, golden: 0 },
    inventoryKeys: { regular: 0, silver: 0, golden: 0 },
    removeAds: false,
    ownedIapProducts: [],
    ownedSkins: ['classic_poop'],
    equippedSkinId: 'classic_poop',
    unlockedWorlds: ['home_bathroom'],
    currentWorldId: 'home_bathroom',
    achievements: {},
    dailyChallenges: [],
    dailyChallengeDate: null,
    dailyChestClaimed: false,
    dailyRerollsUsed: 0,
    dailyChallengesCompletedTotal: 0,
    dailyStreak: 0,
    dailyStreakCycle: 1,
    lastDailyClaim: null,
    streakSaverCharges: 1,
    lastStreakSaverEarnDate: null,
    bathroomBreakCharges: 0,
    lastBathroomBreakGeneration: now,
    firstFlushOfDayClaimedDate: null,
    goldenPoopsCaught: 0,
    clogsCompleted: 0,
    clogsFailed: 0,
    eventsCompleted: 0,
    eventCompletions: {},
    dailyDumpState: {
      lastPlayedDate: null,
      bestScore: 0,
      lastScore: 0,
      lastTier: 'none',
      rewardClaimed: false,
      activeRuntime: null,
      weeklyBestWeekKey: null,
      weeklyBestScore: 0,
    },
    sessionMissions: {
      dateKey: null,
      missions: [],
    },
    rewardedCooldowns: {
      incomeBoostAt: 0,
      instantPpsAt: 0,
      eventRetryAt: 0,
      goldenSpawnAt: 0,
    },
    activeBoosts: [],
    activeEvent: null,
    lastEventEndedAt: {},
    lastGoldenPoopAt: 0,
    nextGoldenPoopAt: now + 60_000 + Math.random() * 180_000,
    nextRandomEventAt: now + 60_000 + Math.random() * 180_000,
    lastEventActivityAt: now,
    autoBuyUnlocked: false,
    autoBuyEnabled: false,
    autoBuyPreferences: {
      generators: true,
      upgrades: true,
    },
    permanentProductionBonus: 0,
    tutorialFlags: {
      core: false,
      generators: false,
      events: false,
      daily: false,
      flush: false,
      collection: false,
      notificationPromptShown: false,
    },
    lastSaveTimestamp: now,
    lastActiveTimestamp: now,
    totalPlayTimeMs: 0,
    officeSessionMs: 0,
    buyMultiplierIndex: 0,
    sessionsCount: 0,
    bathroomBreakClaimsTotal: 0,
    settings: {
      reducedMotion: false,
      haptics: true,
      sfx: true,
      music: true,
      notifications: true,
    },
  }
}
