import type { AchievementDef, AchievementMetric } from '../core/types/gameTypes'

function tiered(
  prefix: string,
  category: AchievementDef['category'],
  metric: AchievementMetric,
  names: string[],
  targets: number[],
  rewardGtp: number[],
  icon: string,
  hidden = false,
): AchievementDef[] {
  return targets.map((target, i) => ({
    id: `${prefix}_${target}`,
    name: names[i] ?? `${prefix} ${target}`,
    description: `Reach ${target.toLocaleString()} ${metric}.`,
    category,
    hidden,
    metric,
    target,
    tier: i + 1,
    rewardGtp: rewardGtp[i] ?? 5,
    icon,
  }))
}

export const ACHIEVEMENTS: AchievementDef[] = [
  ...tiered(
    'taps',
    'tapping',
    'tapCount',
    [
      'Finger Warm-Up',
      'Professional Pooper',
      'Tap Addict',
      'Finger Destroyer',
      'Touchscreen Warranty',
      'Tapocalypse',
      'Infinite Index Finger',
      'Tap Singularity',
    ],
    [100, 1_000, 10_000, 100_000, 1_000_000, 10_000_000, 100_000_000, 1_000_000_000],
    [5, 10, 15, 25, 40, 60, 80, 120],
    'tap',
  ),
  ...tiered(
    'pp',
    'pp',
    'lifetimePPEarned',
    [
      'First Deposit',
      'Bowl Banker',
      'Millionaire Movement',
      'Billionaire Bathroom',
      'Trillion Throne',
      'Qa Club',
      'Qi Crisis',
      'Sx Supreme',
    ],
    [1_000, 1_000_000, 1e9, 1e12, 1e15, 1e18, 1e21, 1e24],
    [5, 15, 25, 40, 60, 90, 120, 180],
    'pp',
  ),
  ...tiered(
    'cps',
    'cps',
    'highestCPS',
    ['Speedy Pooper', 'Bathroom Athlete', 'Fingers on Fire', 'Human Auto-Clicker', 'Are You Okay?'],
    [5, 8, 10, 12, 15],
    [10, 15, 20, 30, 50],
    'cps',
  ),
  ...tiered(
    'flush',
    'flush',
    'flushCount',
    [
      'First Flush',
      'Flush Hobbyist',
      'Flush Professional',
      'Flush Tycoon',
      'Flush Magnate',
      'Flush Immortal',
      'Flush Myth',
    ],
    [1, 5, 10, 25, 50, 100, 250],
    [20, 30, 40, 60, 100, 150, 250],
    'flush',
  ),
  ...tiered(
    'golden',
    'golden',
    'goldenPoopsCaught',
    [
      'Lucky Catch',
      'Golden Hobby',
      'Midas Bathroom',
      'Gilded Instinct',
      'Treasure Toilet',
      'Golden Empire',
    ],
    [1, 10, 25, 50, 100, 250],
    [10, 20, 35, 50, 80, 120],
    'golden',
  ),
  ...tiered(
    'clogs',
    'clogs',
    'clogsCompleted',
    [
      'Unclogged',
      'Plumber Friend',
      'Drain Doctor',
      'Pipe Whisperer',
      'Clog Conqueror',
      'Sewer Sage',
    ],
    [1, 10, 25, 50, 100, 250],
    [10, 20, 35, 50, 80, 120],
    'clog',
  ),
  ...tiered(
    'gens_total',
    'generators',
    'totalGeneratorLevels',
    [
      'Hiring Spree',
      'Staff Meeting',
      'Plumbing Corp',
      'Generator Baron',
      'Idle Empire',
      'Level Avalanche',
    ],
    [10, 50, 100, 250, 500, 1000],
    [10, 20, 30, 50, 80, 120],
    'generator',
  ),
  ...tiered(
    'gens_level',
    'generators',
    'highestGeneratorLevel',
    ['First Hundred', 'Quarter Master', 'Half Legend', 'Thousand Club'],
    [100, 250, 500, 1000],
    [25, 50, 80, 150],
    'generator',
  ),
  ...tiered(
    'skins',
    'collection',
    'ownedSkins',
    ['Wardrobe Starter', 'Fashion Fiber', 'Cosmetic Collector', 'Closet Chaos', 'Skin Tycoon'],
    [3, 8, 15, 25, 40],
    [10, 20, 35, 60, 100],
    'skin',
  ),
  ...tiered(
    'worlds',
    'collection',
    'unlockedWorlds',
    ['Tourist', 'Traveler', 'World Hopper', 'Bathroom Nomad', 'Omni Tourist'],
    [2, 4, 6, 9, 12],
    [15, 25, 40, 70, 120],
    'world',
  ),
  ...tiered(
    'achievements_meta',
    'collection',
    'achievementsCompleted',
    [
      'Badge Beginner',
      'Trophy Curious',
      'Medal Machine',
      'Achievement Addict',
      'Completionist Core',
    ],
    [5, 15, 30, 50, 80],
    [10, 25, 40, 70, 120],
    'badge',
  ),
  ...tiered(
    'events',
    'events',
    'eventsCompleted',
    ['Eventful', 'Chaos Coordinator', 'Drama Magnet', 'Incident Manager', 'Event Horizon'],
    [1, 10, 25, 50, 100],
    [10, 20, 35, 60, 100],
    'event',
  ),
  ...tiered(
    'daily_done',
    'collection',
    'dailyChallengesCompleted',
    ['Daily Curious', 'Routine Royalty', 'Challenge Champ', 'Toilet Scheduler'],
    [3, 15, 30, 60],
    [15, 30, 50, 100],
    'daily',
  ),
  ...tiered(
    'pps',
    'pp',
    'highestPPS',
    [
      'Steady Drip',
      'Pipe Pressure',
      'Industrial Output',
      'This Is Getting Serious',
      'Reality Leak',
    ],
    [10, 1_000, 1_000_000, 1e12, 1e18],
    [10, 25, 50, 100, 200],
    'pps',
  ),

  // Hidden
  {
    id: 'session_taps_1k',
    name: 'Too Much Information',
    description: '1,000 taps in one session.',
    category: 'hidden',
    hidden: true,
    metric: 'sessionTapCount',
    target: 1000,
    tier: 1,
    rewardGtp: 40,
    rewardSkinId: 'vampire_poop',
    icon: 'hidden',
  },
  {
    id: 'office_long_session',
    name: 'Boss Makes a Dollar',
    description: 'Spend 30 minutes in Castle Keep.',
    category: 'hidden',
    hidden: true,
    metric: 'officeSessionMs',
    target: 30 * 60_000,
    tier: 1,
    rewardGtp: 50,
    icon: 'hidden',
  },
  {
    id: 'flush_corny',
    name: 'Corn Identity Crisis',
    description: 'Flush while wearing Corny Poop.',
    category: 'hidden',
    hidden: true,
    metric: 'flushWithSkin',
    target: 1,
    tier: 1,
    rewardGtp: 35,
    icon: 'hidden',
    meta: { skinId: 'corny_poop' },
  },
  {
    id: 'golden_session_5',
    name: 'Golden Shower... Wait, No',
    description: 'Catch 5 Golden Poops in one session.',
    category: 'hidden',
    hidden: true,
    metric: 'goldenInSession',
    target: 5,
    tier: 1,
    rewardGtp: 45,
    icon: 'hidden',
  },
  {
    id: 'clog_fail_5',
    name: 'Call a Plumber',
    description: 'Fail 5 clog events.',
    category: 'hidden',
    hidden: true,
    metric: 'clogsFailed',
    target: 5,
    tier: 1,
    rewardGtp: 30,
    icon: 'hidden',
  },
  {
    id: 'touch_grass',
    name: 'Touch Grass',
    description: 'Return after 48 hours away.',
    category: 'hidden',
    hidden: true,
    metric: 'absenceMs',
    target: 48 * 60 * 60_000,
    tier: 1,
    rewardGtp: 60,
    icon: 'hidden',
  },
  {
    id: 'collection_100',
    name: 'Museum of Swirl',
    description: 'Reach 100% collection progress.',
    category: 'collection',
    hidden: false,
    metric: 'collectionPercent',
    target: 100,
    tier: 1,
    rewardGtp: 300,
    icon: 'collection',
  },
]

// Attach corny skin reward to taps_1000
const taps1k = ACHIEVEMENTS.find((a) => a.id === 'taps_1000')
if (taps1k) taps1k.rewardSkinId = 'corny_poop'

const gens1000 = ACHIEVEMENTS.find((a) => a.id === 'gens_level_1000')
if (gens1000) gens1000.rewardSkinId = 'developer_poop'

const flush50 = ACHIEVEMENTS.find((a) => a.id === 'flush_50')
if (flush50) flush50.rewardSkinId = 'schrodingers_poop'

export const ACHIEVEMENT_BY_ID = Object.fromEntries(ACHIEVEMENTS.map((a) => [a.id, a]))
