/**
 * Central asset manifest.
 * Visuals currently use procedural/CSS reusable variants keyed by these ids.
 * Final-art raster assets are not bundled; integration hooks resolve by id.
 */
export const ASSET_MANIFEST = {
  skins: {
    classic_poop: { variant: 'default', color: '#8B5A2B', status: 'procedural' },
    corny_poop: { variant: 'chunky', color: '#C4A35A', status: 'procedural' },
    coffee_poop: { variant: 'jitter', color: '#4B2E1E', status: 'procedural' },
    burrito_poop: { variant: 'soft', color: '#A67C52', status: 'procedural' },
    taco_poop: { variant: 'crunch', color: '#D4A017', status: 'procedural' },
    office_poop: { variant: 'tie', color: '#5C4033', status: 'procedural' },
    gamer_poop: { variant: 'rgb', color: '#7B2CBF', status: 'procedural' },
    construction_poop: { variant: 'helmet', color: '#E67E22', status: 'procedural' },
    chef_poop: { variant: 'hat', color: '#F5F5F5', status: 'procedural' },
    doctor_poop: { variant: 'stethoscope', color: '#ECF0F1', status: 'procedural' },
    cactus_poop: { variant: 'spiky', color: '#2E8B57', status: 'procedural' },
    cowboy_poop: { variant: 'hat_tip', color: '#A0522D', status: 'procedural' },
    pirate_poop: { variant: 'eyepatch', color: '#2C3E50', status: 'procedural' },
    rainbow_poop: { variant: 'prism', color: '#FF6BCB', status: 'procedural' },
    disco_poop: { variant: 'disco', color: '#9B59B6', status: 'procedural' },
    ghost_poop: { variant: 'fade', color: '#D5DBDB', status: 'procedural' },
    zombie_poop: { variant: 'lurch', color: '#7D8F69', status: 'procedural' },
    vampire_poop: { variant: 'cape', color: '#6C1D45', status: 'procedural' },
    pumpkin_poop: { variant: 'carve', color: '#E67E22', status: 'procedural' },
    santa_poop: { variant: 'jolly', color: '#C0392B', status: 'procedural' },
    unicorn_poop: { variant: 'sparkle', color: '#F8C8DC', status: 'procedural' },
    alien_poop: { variant: 'float', color: '#2ECC71', status: 'procedural' },
    astronaut_poop: { variant: 'zero_g', color: '#BDC3C7', status: 'procedural' },
    viking_poop: { variant: 'horn', color: '#7F8C8D', status: 'procedural' },
    samurai_poop: { variant: 'katana', color: '#34495E', status: 'procedural' },
    knight_poop: { variant: 'armor', color: '#95A5A6', status: 'procedural' },
    wizard_poop: { variant: 'staff', color: '#5B2C6F', status: 'procedural' },
    devil_poop: { variant: 'horns', color: '#922B21', status: 'procedural' },
    angel_poop: { variant: 'halo', color: '#FCF3CF', status: 'procedural' },
    diamond_poop: { variant: 'crystal', color: '#AED6F1', status: 'procedural' },
    cyber_poop: { variant: 'neon', color: '#00F5FF', status: 'procedural' },
    pixel_poop: { variant: 'pixel', color: '#E74C3C', status: 'procedural' },
    glitch_poop: { variant: 'glitch', color: '#1ABC9C', status: 'procedural' },
    nuclear_poop: { variant: 'glow', color: '#A8FF3E', status: 'procedural' },
    king_poop: { variant: 'crown', color: '#F4D03F', status: 'procedural' },
    black_hole_poop: { variant: 'singularity', color: '#1C1C1C', status: 'procedural' },
    holographic_poop: { variant: 'holo', color: '#85C1E9', status: 'procedural' },
    time_traveller_poop: { variant: 'chrono', color: '#5DADE2', status: 'procedural' },
    multiverse_poop: { variant: 'split', color: '#AF7AC5', status: 'procedural' },
    void_poop: { variant: 'void', color: '#2C003E', status: 'procedural' },
    developer_poop: { variant: 'coffee_code', color: '#273746', status: 'procedural' },
    ceo_poop: { variant: 'suit', color: '#1A5276', status: 'procedural' },
    '404_poop': { variant: 'error', color: '#E74C3C', status: 'procedural' },
    schrodingers_poop: { variant: 'box', color: '#ABB2B9', status: 'procedural' },
    the_final_poop: { variant: 'final', color: '#F5B041', status: 'procedural' },
  },
  animations: {
    idle: { status: 'procedural' },
    slow: { status: 'procedural' },
    active: { status: 'procedural' },
    fast: { status: 'procedural' },
    frenzy: { status: 'procedural' },
    overdrive: { status: 'procedural' },
    flush: { status: 'procedural' },
    unlock: { status: 'procedural' },
    event: { status: 'procedural' },
  },
  vfx: {
    tap_particles: { status: 'procedural' },
    crit_burst: { status: 'procedural' },
    golden_glow: { status: 'procedural' },
    frenzy_aura: { status: 'procedural' },
    overdrive_aura: { status: 'procedural' },
  },
  uiIcons: {
    daily: { status: 'procedural' },
    achievements: { status: 'procedural' },
    collection: { status: 'procedural' },
    flush: { status: 'procedural' },
    royal: { status: 'procedural' },
  },
  events: {
    golden_poop: { status: 'procedural' },
    clogged_toilet: { status: 'procedural' },
    burrito_rush: { status: 'procedural' },
    toilet_paper_storm: { status: 'procedural' },
    plumber_inspection: { status: 'procedural' },
    mega_clog: { status: 'procedural' },
    toilet_quake: { status: 'procedural' },
    golden_rain: { status: 'procedural' },
    mystery_flush: { status: 'procedural' },
  },
  worlds: {
    home_bathroom: { status: 'procedural' },
    office_toilet: { status: 'procedural' },
    gas_station_restroom: { status: 'procedural' },
    stadium_loo: { status: 'procedural' },
    space_loo: { status: 'procedural' },
    quantum_bathroom: { status: 'procedural' },
    chrono_chamber: { status: 'procedural' },
    neon_arcade_stall: { status: 'procedural' },
    volcanic_spa_toilet: { status: 'procedural' },
    cloud_restroom: { status: 'procedural' },
    void_washroom: { status: 'procedural' },
    omni_throne: { status: 'procedural' },
  },
  missingFinalArt: [
    'All skin raster/illustration finals',
    'World background illustration finals',
    'Event character art finals',
  ],
} as const
