import type { ChallengeTemplate } from '../core/types/gameTypes'

export const CHALLENGE_TEMPLATES: ChallengeTemplate[] = [
  // Activity
  {
    id: 'tap_n',
    category: 'activity',
    metric: 'taps',
    name: 'Tap Duty',
    description: 'Perform taps',
    baseTarget: 200,
    scaling: 'taps',
    rewardGtp: 8,
  },
  {
    id: 'crit_n',
    category: 'activity',
    metric: 'crit_taps',
    name: 'Critical Condition',
    description: 'Land critical taps',
    baseTarget: 10,
    scaling: 'taps',
    rewardGtp: 10,
  },
  {
    id: 'cps_reach',
    category: 'activity',
    metric: 'cps',
    name: 'Speed Run to the Stall',
    description: 'Reach CPS',
    baseTarget: 6,
    scaling: 'none',
    rewardGtp: 12,
  },
  {
    id: 'combo_reach',
    category: 'activity',
    metric: 'combo',
    name: 'Combo Courtesy',
    description: 'Reach combo',
    baseTarget: 15,
    scaling: 'none',
    rewardGtp: 12,
  },
  {
    id: 'frenzy_once',
    category: 'activity',
    metric: 'frenzy',
    name: 'Frenzy Friday (Any Day)',
    description: 'Enter Frenzy',
    baseTarget: 1,
    scaling: 'none',
    rewardGtp: 15,
  },
  {
    id: 'tap_pp',
    category: 'activity',
    metric: 'tap_pp',
    name: 'Handmade PP',
    description: 'Earn PP from tapping',
    baseTarget: 500,
    scaling: 'pps',
    rewardGtp: 10,
  },

  // Economy
  {
    id: 'buy_gens',
    category: 'economy',
    metric: 'generator_levels',
    name: 'Hire Help',
    description: 'Buy generator levels',
    baseTarget: 5,
    scaling: 'generators',
    rewardGtp: 10,
  },
  {
    id: 'buy_upgrades',
    category: 'economy',
    metric: 'upgrades',
    name: 'Upgrade Impulse',
    description: 'Buy upgrades',
    baseTarget: 2,
    scaling: 'none',
    rewardGtp: 10,
  },
  {
    id: 'idle_pp',
    category: 'economy',
    metric: 'idle_pp',
    name: 'Passive Aggressive',
    description: 'Earn idle PP',
    baseTarget: 1_000,
    scaling: 'pps',
    rewardGtp: 12,
  },
  {
    id: 'spend_pp',
    category: 'economy',
    metric: 'spend_pp',
    name: 'Retail Therapy',
    description: 'Spend PP',
    baseTarget: 2_000,
    scaling: 'pps',
    rewardGtp: 12,
  },
  {
    id: 'gen_level',
    category: 'economy',
    metric: 'generator_level',
    name: 'Level Ambition',
    description: 'Reach a generator level',
    baseTarget: 10,
    scaling: 'generators',
    rewardGtp: 15,
  },

  // Event
  {
    id: 'golden_n',
    category: 'event',
    metric: 'golden_poops',
    name: 'Gold Rush Lite',
    description: 'Catch Golden Poops',
    baseTarget: 2,
    scaling: 'none',
    rewardGtp: 15,
  },
  {
    id: 'clog_n',
    category: 'event',
    metric: 'clogs',
    name: 'Declog Duty',
    description: 'Complete Clogged Toilet',
    baseTarget: 1,
    scaling: 'none',
    rewardGtp: 15,
  },
  {
    id: 'events_n',
    category: 'event',
    metric: 'events',
    name: 'Chaos Collector',
    description: 'Complete events',
    baseTarget: 2,
    scaling: 'flush',
    rewardGtp: 15,
  },
  {
    id: 'flush_once',
    category: 'event',
    metric: 'flush',
    name: 'Ceremonial Flush',
    description: 'Perform a Flush',
    baseTarget: 1,
    scaling: 'none',
    rewardGtp: 25,
  },
  {
    id: 'frenzy_complete',
    category: 'event',
    metric: 'frenzy_complete',
    name: 'Ride the Wave',
    description: 'Complete a Frenzy window',
    baseTarget: 1,
    scaling: 'none',
    rewardGtp: 18,
  },
]

export const CHALLENGE_BY_ID = Object.fromEntries(CHALLENGE_TEMPLATES.map((c) => [c.id, c]))
