import type { EventDef } from '../core/types/gameTypes'

export const EVENTS: EventDef[] = [
  {
    id: 'golden_poop',
    type: 'golden_poop',
    name: 'Golden Poop',
    description: 'Catch it before it escapes dignity.',
    durationMs: 8_000,
    cooldownMs: 120_000,
    minFlushCount: 0,
    rewardGtp: 5,
    rewardPpMinutes: 3,
    uiPresentation: 'floating_target',
    analyticsId: 'event_golden_poop',
  },
  {
    id: 'clogged_toilet',
    type: 'clogged_toilet',
    name: 'Clogged Toilet',
    description: 'Tap to clear the crisis.',
    durationMs: 15_000,
    cooldownMs: 180_000,
    minFlushCount: 0,
    rewardGtp: 8,
    rewardPpMinutes: 5,
    tapTarget: 40,
    uiPresentation: 'boss_bar',
    analyticsId: 'event_clogged_toilet',
  },
  {
    id: 'burrito_rush',
    type: 'burrito_rush',
    name: 'Burrito Rush',
    description: 'Tap power goes spicy.',
    durationMs: 20_000,
    cooldownMs: 240_000,
    minFlushCount: 0,
    rewardGtp: 6,
    rewardPpMinutes: 2,
    uiPresentation: 'banner_boost',
    analyticsId: 'event_burrito_rush',
  },
  {
    id: 'toilet_paper_storm',
    type: 'toilet_paper_storm',
    name: 'Toilet Paper Storm',
    description: 'Catch flying rolls.',
    durationMs: 18_000,
    cooldownMs: 260_000,
    minFlushCount: 1,
    rewardGtp: 10,
    rewardPpMinutes: 4,
    tapTarget: 20,
    uiPresentation: 'falling_objects',
    analyticsId: 'event_tp_storm',
  },
  {
    id: 'plumber_inspection',
    type: 'plumber_inspection',
    name: 'Plumber Inspection',
    description: 'Hold a steady CPS.',
    durationMs: 12_000,
    cooldownMs: 300_000,
    minFlushCount: 1,
    rewardGtp: 12,
    rewardPpMinutes: 4,
    tapTarget: 8,
    uiPresentation: 'cps_meter',
    analyticsId: 'event_plumber_inspection',
  },
  {
    id: 'mega_clog',
    type: 'mega_clog',
    name: 'Mega Clog',
    description: 'Mini-boss of the pipes.',
    durationMs: 25_000,
    cooldownMs: 420_000,
    minFlushCount: 3,
    rewardGtp: 20,
    rewardPpMinutes: 10,
    tapTarget: 120,
    uiPresentation: 'boss_bar',
    analyticsId: 'event_mega_clog',
  },
  {
    id: 'toilet_quake',
    type: 'toilet_quake',
    name: 'Toilet Quake',
    description: 'Everything produces harder.',
    durationMs: 30_000,
    cooldownMs: 360_000,
    minFlushCount: 2,
    rewardGtp: 10,
    rewardPpMinutes: 6,
    uiPresentation: 'screen_shake_boost',
    analyticsId: 'event_toilet_quake',
  },
  {
    id: 'golden_rain',
    type: 'golden_rain',
    name: 'Golden Rain',
    description: 'Multiple golden targets.',
    durationMs: 16_000,
    cooldownMs: 480_000,
    minFlushCount: 5,
    rewardGtp: 25,
    rewardPpMinutes: 8,
    tapTarget: 5,
    uiPresentation: 'multi_target',
    analyticsId: 'event_golden_rain',
  },
  {
    id: 'mystery_flush',
    type: 'mystery_flush',
    name: 'Mystery Flush',
    description: 'Pick a reward door.',
    durationMs: 20_000,
    cooldownMs: 500_000,
    minFlushCount: 4,
    rewardGtp: 30,
    rewardPpMinutes: 7,
    uiPresentation: 'choice_cards',
    analyticsId: 'event_mystery_flush',
  },
]

export const EVENT_BY_ID = Object.fromEntries(EVENTS.map((e) => [e.id, e]))
