import type { GeneratorDef } from '../core/types/gameTypes'

const STANDARD_MILESTONES = [
  { level: 10, productionMultiplier: 2 },
  { level: 25, productionMultiplier: 2 },
  { level: 50, productionMultiplier: 3 },
  { level: 100, productionMultiplier: 3 },
  { level: 250, productionMultiplier: 4 },
  { level: 500, productionMultiplier: 5 },
  { level: 1000, productionMultiplier: 10 },
]

function g(
  partial: Omit<GeneratorDef, 'milestones'> & { milestones?: GeneratorDef['milestones'] },
): GeneratorDef {
  return { milestones: STANDARD_MILESTONES, ...partial }
}

export const GENERATORS: GeneratorDef[] = [
  g({
    id: 'plunger_intern',
    name: 'Plunger Intern',
    description: 'Works for exposure and mild trauma.',
    baseCost: 15,
    costGrowth: 1.12,
    baseProduction: 0.1,
  }),
  g({
    id: 'fiber_farmer',
    name: 'Fiber Farmer',
    description: 'Harvests oats with suspicious dedication.',
    baseCost: 100,
    costGrowth: 1.13,
    baseProduction: 1,
    unlockPP: 50,
  }),
  g({
    id: 'bathroom_bard',
    name: 'Bathroom Bard',
    description: 'Sings motivational flush anthems.',
    baseCost: 1_100,
    costGrowth: 1.14,
    baseProduction: 8,
    unlockPP: 500,
  }),
  g({
    id: 'portapotty_fleet',
    name: 'Porta-Potty Fleet',
    description: 'Mobile relief with questionable GPS.',
    baseCost: 12_000,
    costGrowth: 1.15,
    baseProduction: 47,
    unlockPP: 5_000,
  }),
  g({
    id: 'sewer_syndicate',
    name: 'Sewer Syndicate',
    description: 'Unionized sludge with benefits.',
    baseCost: 130_000,
    costGrowth: 1.15,
    baseProduction: 260,
    unlockPP: 50_000,
  }),
  g({
    id: 'chili_refinery',
    name: 'Chili Refinery',
    description: 'Processes spice into pure urgency.',
    baseCost: 1_400_000,
    costGrowth: 1.16,
    baseProduction: 1_400,
    unlockPP: 400_000,
  }),
  g({
    id: 'office_toilet_network',
    name: 'Office Toilet Network',
    description: 'Corporate plumbing, unpaid overtime.',
    baseCost: 20_000_000,
    costGrowth: 1.16,
    baseProduction: 7_800,
    unlockPP: 5_000_000,
  }),
  g({
    id: 'luxury_bidet_lab',
    name: 'Luxury Bidet Lab',
    description: 'Science, but splashier.',
    baseCost: 330_000_000,
    costGrowth: 1.17,
    baseProduction: 44_000,
    unlockPP: 80_000_000,
  }),
  g({
    id: 'space_station_loo',
    name: 'Space Station Loo',
    description: 'Zero-G requires advanced technique.',
    baseCost: 5_100_000_000,
    costGrowth: 1.17,
    baseProduction: 260_000,
    unlockPP: 1_000_000_000,
  }),
  g({
    id: 'quantum_septic',
    name: 'Quantum Septic Tank',
    description: 'Both empty and full until observed.',
    baseCost: 75_000_000_000,
    costGrowth: 1.18,
    baseProduction: 1_600_000,
    unlockPP: 20_000_000_000,
    unlockFlushCount: 1,
  }),
  g({
    id: 'temporal_restroom',
    name: 'Temporal Restroom',
    description: 'You already flushed yesterday tomorrow.',
    baseCost: 1_000_000_000_000,
    costGrowth: 1.18,
    baseProduction: 10_000_000,
    unlockFlushCount: 3,
  }),
  g({
    id: 'galactic_septic_tank',
    name: 'Galactic Septic Tank',
    description: 'Holds civilizations. Barely.',
    baseCost: 14_000_000_000_000,
    costGrowth: 1.19,
    baseProduction: 65_000_000,
    unlockFlushCount: 5,
  }),
  g({
    id: 'black_hole_plumber',
    name: 'Black Hole Plumber',
    description: 'Nothing escapes. Not even excuses.',
    baseCost: 170_000_000_000_000,
    costGrowth: 1.19,
    baseProduction: 430_000_000,
    unlockFlushCount: 8,
  }),
  g({
    id: 'multiverse_bidet_network',
    name: 'Multiverse Bidet Network',
    description: 'Infinite cheeks, synchronized rinse.',
    baseCost: 2.1e15,
    costGrowth: 1.2,
    baseProduction: 2.9e9,
    unlockFlushCount: 10,
  }),
  g({
    id: 'chrono_toilet',
    name: 'Chrono Toilet',
    description: 'Schedules bowel movements across eras.',
    baseCost: 2.6e16,
    costGrowth: 1.2,
    baseProduction: 2.1e10,
    unlockFlushCount: 12,
  }),
  g({
    id: 'reality_recycling_plant',
    name: 'Reality Recycling Plant',
    description: 'Turns plot holes into fiber.',
    baseCost: 3.1e17,
    costGrowth: 1.21,
    baseProduction: 1.5e11,
    unlockFlushCount: 15,
  }),
  g({
    id: 'cosmic_colon_collider',
    name: 'Cosmic Colon Collider',
    description: 'Accelerates particles of destiny.',
    baseCost: 3.8e18,
    costGrowth: 1.21,
    baseProduction: 1.1e12,
    unlockFlushCount: 20,
  }),
  g({
    id: 'universal_brown_matter_reactor',
    name: 'Universal Brown Matter Reactor',
    description: 'Clean energy. Dirty jokes.',
    baseCost: 4.6e19,
    costGrowth: 1.22,
    baseProduction: 8.3e12,
    unlockFlushCount: 25,
  }),
  g({
    id: 'infinite_bathroom_bureaucracy',
    name: 'Infinite Bathroom Bureaucracy',
    description: 'Please take a number. Forever.',
    baseCost: 5.5e20,
    costGrowth: 1.22,
    baseProduction: 6.2e13,
    unlockFlushCount: 35,
  }),
  g({
    id: 'toilet_singularity',
    name: 'Toilet Singularity',
    description: 'The swirl that ends swirls.',
    baseCost: 6.6e21,
    costGrowth: 1.23,
    baseProduction: 4.7e14,
    unlockFlushCount: 50,
  }),
  g({
    id: 'omniversal_sewer',
    name: 'Omniversal Sewer',
    description: 'All pipes lead here. All of them.',
    baseCost: 8e22,
    costGrowth: 1.24,
    baseProduction: 3.5e15,
    unlockFlushCount: 75,
  }),
  g({
    id: 'final_flush_foundry',
    name: 'Final Flush Foundry',
    description: 'Forges legends from leftover burrito.',
    baseCost: 1e24,
    costGrowth: 1.25,
    baseProduction: 2.5e16,
    unlockFlushCount: 100,
  }),
]

export const GENERATOR_BY_ID = Object.fromEntries(GENERATORS.map((x) => [x.id, x]))
