import type { RoyalFlushNodeDef } from '../core/types/gameTypes'

function node(partial: RoyalFlushNodeDef): RoyalFlushNodeDef {
  return partial
}

export const ROYAL_FLUSH_NODES: RoyalFlushNodeDef[] = [
  // PRESSURE
  node({
    id: 'rf_tap_1',
    category: 'pressure',
    name: 'Firm Sit',
    description: '+Tap power',
    maxLevel: 10,
    baseCost: 5,
    costGrowth: 1.45,
    effectType: 'tap_power',
    effectValue: 0.08,
    requires: [],
    unlockFlushCount: 1,
  }),
  node({
    id: 'rf_tap_2',
    category: 'pressure',
    name: 'Power Legs',
    description: '+Tap multiplier',
    maxLevel: 10,
    baseCost: 12,
    costGrowth: 1.5,
    effectType: 'tap_multiplier',
    effectValue: 0.1,
    requires: ['rf_tap_1'],
    unlockFlushCount: 1,
  }),
  node({
    id: 'rf_crit_1',
    category: 'pressure',
    name: 'Lucky Elbow',
    description: '+Crit chance',
    maxLevel: 8,
    baseCost: 15,
    costGrowth: 1.55,
    effectType: 'crit_chance',
    effectValue: 0.01,
    requires: ['rf_tap_1'],
    unlockFlushCount: 1,
  }),
  node({
    id: 'rf_crit_2',
    category: 'pressure',
    name: 'Critical Plumbing',
    description: '+Crit multiplier',
    maxLevel: 8,
    baseCost: 25,
    costGrowth: 1.6,
    effectType: 'crit_multiplier',
    effectValue: 0.4,
    requires: ['rf_crit_1'],
    unlockFlushCount: 2,
  }),
  node({
    id: 'rf_combo_click',
    category: 'pressure',
    name: 'Click Cadence',
    description: '+Combo max',
    maxLevel: 8,
    baseCost: 20,
    costGrowth: 1.55,
    effectType: 'combo_max',
    effectValue: 2,
    requires: ['rf_tap_2'],
    unlockFlushCount: 2,
  }),
  node({
    id: 'rf_tap_3',
    category: 'pressure',
    name: 'Titanium Thumb',
    description: '+Tap multiplier',
    maxLevel: 12,
    baseCost: 40,
    costGrowth: 1.6,
    effectType: 'tap_multiplier',
    effectValue: 0.12,
    requires: ['rf_tap_2'],
    unlockFlushCount: 5,
  }),

  // PLUMBING
  node({
    id: 'rf_gen_1',
    category: 'plumbing',
    name: 'Pipe Grease',
    description: '+Generator production',
    maxLevel: 10,
    baseCost: 8,
    costGrowth: 1.5,
    effectType: 'generator_production',
    effectValue: 0.1,
    requires: [],
    unlockFlushCount: 1,
  }),
  node({
    id: 'rf_gen_2',
    category: 'plumbing',
    name: 'Union Benefits',
    description: '+Generator production',
    maxLevel: 10,
    baseCost: 20,
    costGrowth: 1.55,
    effectType: 'generator_production',
    effectValue: 0.12,
    requires: ['rf_gen_1'],
    unlockFlushCount: 1,
  }),
  node({
    id: 'rf_idle_1',
    category: 'plumbing',
    name: 'Gravity Assist',
    description: '+Idle output',
    maxLevel: 10,
    baseCost: 15,
    costGrowth: 1.5,
    effectType: 'idle_multiplier',
    effectValue: 0.1,
    requires: ['rf_gen_1'],
    unlockFlushCount: 2,
  }),
  node({
    id: 'rf_global_1',
    category: 'plumbing',
    name: 'Main Line Boost',
    description: '+Global production',
    maxLevel: 8,
    baseCost: 35,
    costGrowth: 1.65,
    effectType: 'global_production',
    effectValue: 0.08,
    requires: ['rf_gen_2'],
    unlockFlushCount: 3,
  }),
  node({
    id: 'rf_gen_3',
    category: 'plumbing',
    name: 'Industrial Valves',
    description: '+Generator production',
    maxLevel: 12,
    baseCost: 50,
    costGrowth: 1.6,
    effectType: 'generator_production',
    effectValue: 0.15,
    requires: ['rf_global_1'],
    unlockFlushCount: 8,
  }),
  node({
    id: 'rf_milestone_echo',
    category: 'plumbing',
    name: 'Milestone Echo',
    description: '+Global production from milestones',
    maxLevel: 6,
    baseCost: 70,
    costGrowth: 1.7,
    effectType: 'global_production',
    effectValue: 0.1,
    requires: ['rf_gen_3'],
    unlockFlushCount: 12,
  }),

  // COMBO
  node({
    id: 'rf_combo_1',
    category: 'combo',
    name: 'Slow Fade',
    description: 'Slower combo decay',
    maxLevel: 10,
    baseCost: 10,
    costGrowth: 1.5,
    effectType: 'combo_decay',
    effectValue: -0.06,
    requires: [],
    unlockFlushCount: 1,
  }),
  node({
    id: 'rf_combo_2',
    category: 'combo',
    name: 'Higher Ceiling',
    description: '+Combo max',
    maxLevel: 10,
    baseCost: 18,
    costGrowth: 1.55,
    effectType: 'combo_max',
    effectValue: 2,
    requires: ['rf_combo_1'],
    unlockFlushCount: 1,
  }),
  node({
    id: 'rf_frenzy_1',
    category: 'combo',
    name: 'Easy Frenzy',
    description: 'Lower Frenzy threshold',
    maxLevel: 8,
    baseCost: 25,
    costGrowth: 1.6,
    effectType: 'frenzy_threshold',
    effectValue: -0.25,
    requires: ['rf_combo_2'],
    unlockFlushCount: 2,
  }),
  node({
    id: 'rf_frenzy_2',
    category: 'combo',
    name: 'Longer Frenzy',
    description: '+Frenzy duration',
    maxLevel: 8,
    baseCost: 30,
    costGrowth: 1.6,
    effectType: 'frenzy_duration',
    effectValue: 0.75,
    requires: ['rf_frenzy_1'],
    unlockFlushCount: 3,
  }),
  node({
    id: 'rf_combo_3',
    category: 'combo',
    name: 'Combo Vault',
    description: '+Combo max',
    maxLevel: 8,
    baseCost: 55,
    costGrowth: 1.65,
    effectType: 'combo_max',
    effectValue: 3,
    requires: ['rf_frenzy_2'],
    unlockFlushCount: 10,
  }),
  node({
    id: 'rf_overdrive',
    category: 'combo',
    name: 'Overdrive Primer',
    description: 'Easier Overdrive entry',
    maxLevel: 5,
    baseCost: 90,
    costGrowth: 1.75,
    effectType: 'frenzy_threshold',
    effectValue: -0.4,
    requires: ['rf_combo_3'],
    unlockFlushCount: 20,
  }),

  // IDLE
  node({
    id: 'rf_offline_1',
    category: 'idle',
    name: 'Night Shift',
    description: '+Idle efficiency',
    maxLevel: 10,
    baseCost: 10,
    costGrowth: 1.5,
    effectType: 'idle_multiplier',
    effectValue: 0.12,
    requires: [],
    unlockFlushCount: 1,
  }),
  node({
    id: 'rf_offline_cap_1',
    category: 'idle',
    name: 'Bigger Tank',
    description: '+1h offline cap',
    maxLevel: 4,
    baseCost: 25,
    costGrowth: 1.8,
    effectType: 'offline_cap',
    effectValue: 1,
    requires: ['rf_offline_1'],
    unlockFlushCount: 1,
  }),
  node({
    id: 'rf_offline_2',
    category: 'idle',
    name: 'Dream Digestion',
    description: '+Idle efficiency',
    maxLevel: 10,
    baseCost: 35,
    costGrowth: 1.55,
    effectType: 'idle_multiplier',
    effectValue: 0.15,
    requires: ['rf_offline_cap_1'],
    unlockFlushCount: 3,
  }),
  node({
    id: 'rf_offline_cap_2',
    category: 'idle',
    name: 'Extended Leave',
    description: '+2h offline cap',
    maxLevel: 4,
    baseCost: 60,
    costGrowth: 1.85,
    effectType: 'offline_cap',
    effectValue: 2,
    requires: ['rf_offline_2'],
    unlockFlushCount: 8,
  }),
  node({
    id: 'rf_gen_idle',
    category: 'idle',
    name: 'Autonomous Interns',
    description: '+Generator production',
    maxLevel: 10,
    baseCost: 45,
    costGrowth: 1.6,
    effectType: 'generator_production',
    effectValue: 0.12,
    requires: ['rf_offline_1'],
    unlockFlushCount: 5,
  }),
  node({
    id: 'rf_offline_cap_3',
    category: 'idle',
    name: 'Weekend Mode',
    description: '+4h offline cap',
    maxLevel: 2,
    baseCost: 120,
    costGrowth: 2.0,
    effectType: 'offline_cap',
    effectValue: 4,
    requires: ['rf_offline_cap_2'],
    unlockFlushCount: 15,
  }),

  // LUCK
  node({
    id: 'rf_gold_1',
    category: 'luck',
    name: 'Shiny Instinct',
    description: 'Golden Poop more often',
    maxLevel: 8,
    baseCost: 12,
    costGrowth: 1.55,
    effectType: 'golden_chance',
    effectValue: 0.08,
    requires: [],
    unlockFlushCount: 1,
  }),
  node({
    id: 'rf_gold_2',
    category: 'luck',
    name: 'Midas Seat',
    description: 'Better Golden rewards',
    maxLevel: 8,
    baseCost: 22,
    costGrowth: 1.6,
    effectType: 'event_reward',
    effectValue: 0.15,
    requires: ['rf_gold_1'],
    unlockFlushCount: 2,
  }),
  node({
    id: 'rf_event_1',
    category: 'luck',
    name: 'Chaos Coupon',
    description: '+Event rewards',
    maxLevel: 8,
    baseCost: 28,
    costGrowth: 1.6,
    effectType: 'event_reward',
    effectValue: 0.2,
    requires: ['rf_gold_1'],
    unlockFlushCount: 3,
  }),
  node({
    id: 'rf_event_2',
    category: 'luck',
    name: 'Incident Magnet',
    description: '+Event rewards',
    maxLevel: 8,
    baseCost: 50,
    costGrowth: 1.65,
    effectType: 'event_reward',
    effectValue: 0.25,
    requires: ['rf_event_1'],
    unlockFlushCount: 8,
  }),
  node({
    id: 'rf_gold_3',
    category: 'luck',
    name: 'Golden Forecast',
    description: 'Much more Golden Poop',
    maxLevel: 6,
    baseCost: 80,
    costGrowth: 1.7,
    effectType: 'golden_chance',
    effectValue: 0.12,
    requires: ['rf_gold_2'],
    unlockFlushCount: 12,
  }),
  node({
    id: 'rf_luck_finale',
    category: 'luck',
    name: 'RNGesus Plumbing',
    description: '+Global luck rewards',
    maxLevel: 5,
    baseCost: 140,
    costGrowth: 1.8,
    effectType: 'event_reward',
    effectValue: 0.35,
    requires: ['rf_event_2', 'rf_gold_3'],
    unlockFlushCount: 25,
  }),
]

export const ROYAL_FLUSH_BY_ID = Object.fromEntries(ROYAL_FLUSH_NODES.map((n) => [n.id, n]))
