import type { SkinDef } from '../core/types/gameTypes'

export const SKINS: SkinDef[] = [
  {
    id: 'classic_poop',
    name: 'Classic Poop',
    description: 'The original swirl celebrity.',
    rarity: 'common',
    unlock: { type: 'default' },
    asset: 'skins/classic_poop',
    animationVariant: 'default',
    vfx: 'none',
  },
  {
    id: 'corny_poop',
    name: 'Corny Poop',
    description: 'Contains visible plot kernels.',
    rarity: 'common',
    unlock: { type: 'achievement', achievementId: 'taps_1000' },
    asset: 'skins/corny_poop',
    animationVariant: 'chunky',
    vfx: 'kernels',
  },
  {
    id: 'coffee_poop',
    name: 'Coffee Poop',
    description: 'Jittery and judgmental.',
    rarity: 'common',
    unlock: { type: 'gtp', amount: 25 },
    asset: 'skins/coffee_poop',
    animationVariant: 'jitter',
    vfx: 'steam',
  },
  {
    id: 'burrito_poop',
    name: 'Burrito Poop',
    description: 'Wrapped in consequences.',
    rarity: 'common',
    unlock: { type: 'gtp', amount: 40 },
    asset: 'skins/burrito_poop',
    animationVariant: 'soft',
    vfx: 'beans',
  },
  {
    id: 'taco_poop',
    name: 'Taco Poop',
    description: 'Crunchy exterior, chaotic interior.',
    rarity: 'rare',
    unlock: { type: 'gtp', amount: 75 },
    asset: 'skins/taco_poop',
    animationVariant: 'crunch',
    vfx: 'salsa',
  },
  {
    id: 'office_poop',
    name: 'Office Poop',
    description: 'Has a calendar invite.',
    rarity: 'rare',
    unlock: { type: 'world', worldId: 'office_toilet' },
    asset: 'skins/office_poop',
    animationVariant: 'tie',
    vfx: 'stapler',
  },
  {
    id: 'gamer_poop',
    name: 'Gamer Poop',
    description: 'Needs a hydration break.',
    rarity: 'rare',
    unlock: { type: 'gtp', amount: 90 },
    asset: 'skins/gamer_poop',
    animationVariant: 'rgb',
    vfx: 'pixels',
  },
  {
    id: 'construction_poop',
    name: 'Construction Poop',
    description: 'Hard hat, soft landing.',
    rarity: 'rare',
    unlock: { type: 'gtp', amount: 100 },
    asset: 'skins/construction_poop',
    animationVariant: 'helmet',
    vfx: 'dust',
  },
  {
    id: 'chef_poop',
    name: 'Chef Poop',
    description: 'Michelin-starred mistake.',
    rarity: 'rare',
    unlock: { type: 'daily', count: 5 },
    asset: 'skins/chef_poop',
    animationVariant: 'hat',
    vfx: 'sparkle_food',
  },
  {
    id: 'doctor_poop',
    name: 'Doctor Poop',
    description: 'Will see you now. Unfortunately.',
    rarity: 'rare',
    unlock: { type: 'gtp', amount: 120 },
    asset: 'skins/doctor_poop',
    animationVariant: 'stethoscope',
    vfx: 'cross',
  },
  {
    id: 'cactus_poop',
    name: 'Cactus Poop',
    description: 'Hydration is ironic here.',
    rarity: 'rare',
    unlock: { type: 'gtp', amount: 110 },
    asset: 'skins/cactus_poop',
    animationVariant: 'spiky',
    vfx: 'needles',
  },
  {
    id: 'cowboy_poop',
    name: 'Cowboy Poop',
    description: 'Yeehaw and yee-ow.',
    rarity: 'rare',
    unlock: { type: 'streak', day: 3 },
    asset: 'skins/cowboy_poop',
    animationVariant: 'hat_tip',
    vfx: 'dust_trail',
  },
  {
    id: 'pirate_poop',
    name: 'Pirate Poop',
    description: 'Seeks the golden flush.',
    rarity: 'rare',
    unlock: { type: 'gtp', amount: 150 },
    asset: 'skins/pirate_poop',
    animationVariant: 'eyepatch',
    vfx: 'waves',
  },
  {
    id: 'rainbow_poop',
    name: 'Rainbow Poop',
    description: 'Taste the fiber spectrum.',
    rarity: 'epic',
    unlock: { type: 'gtp', amount: 250 },
    asset: 'skins/rainbow_poop',
    animationVariant: 'prism',
    vfx: 'rainbow',
  },
  {
    id: 'disco_poop',
    name: 'Disco Poop',
    description: 'Stays alive. On the seat.',
    rarity: 'epic',
    unlock: { type: 'event', eventId: 'burrito_rush', count: 3 },
    asset: 'skins/disco_poop',
    animationVariant: 'disco',
    vfx: 'mirrorball',
  },
  {
    id: 'ghost_poop',
    name: 'Ghost Poop',
    description: 'Boo-wel movement.',
    rarity: 'epic',
    unlock: { type: 'gtp', amount: 280 },
    asset: 'skins/ghost_poop',
    animationVariant: 'fade',
    vfx: 'ectoplasm',
  },
  {
    id: 'zombie_poop',
    name: 'Zombie Poop',
    description: 'Brains optional.',
    rarity: 'epic',
    unlock: { type: 'gtp', amount: 300 },
    asset: 'skins/zombie_poop',
    animationVariant: 'lurch',
    vfx: 'moss',
  },
  {
    id: 'vampire_poop',
    name: 'Vampire Poop',
    description: 'Allergic to morning meetings.',
    rarity: 'epic',
    unlock: { type: 'achievement', achievementId: 'session_taps_1k' },
    asset: 'skins/vampire_poop',
    animationVariant: 'cape',
    vfx: 'bat',
  },
  {
    id: 'pumpkin_poop',
    name: 'Pumpkin Poop',
    description: 'Seasonal and judgmental.',
    rarity: 'epic',
    unlock: { type: 'gtp', amount: 320 },
    asset: 'skins/pumpkin_poop',
    animationVariant: 'carve',
    vfx: 'leaves',
  },
  {
    id: 'santa_poop',
    name: 'Santa Poop',
    description: 'He knows when you have been clogging.',
    rarity: 'epic',
    unlock: { type: 'streak', day: 7 },
    asset: 'skins/santa_poop',
    animationVariant: 'jolly',
    vfx: 'snow',
  },
  {
    id: 'unicorn_poop',
    name: 'Unicorn Poop',
    description: 'Sparkles are non-negotiable.',
    rarity: 'epic',
    unlock: { type: 'gtp', amount: 400 },
    asset: 'skins/unicorn_poop',
    animationVariant: 'sparkle',
    vfx: 'glitter',
  },
  {
    id: 'alien_poop',
    name: 'Alien Poop',
    description: 'Probe complete.',
    rarity: 'epic',
    unlock: { type: 'world', worldId: 'space_loo' },
    asset: 'skins/alien_poop',
    animationVariant: 'float',
    vfx: 'ufo',
  },
  {
    id: 'astronaut_poop',
    name: 'Astronaut Poop',
    description: 'One small squat.',
    rarity: 'epic',
    unlock: { type: 'gtp', amount: 450 },
    asset: 'skins/astronaut_poop',
    animationVariant: 'zero_g',
    vfx: 'stars',
  },
  {
    id: 'viking_poop',
    name: 'Viking Poop',
    description: 'Raids the snack drawer.',
    rarity: 'epic',
    unlock: { type: 'gtp', amount: 420 },
    asset: 'skins/viking_poop',
    animationVariant: 'horn',
    vfx: 'frost',
  },
  {
    id: 'samurai_poop',
    name: 'Samurai Poop',
    description: 'Honor before odor.',
    rarity: 'epic',
    unlock: { type: 'daily', count: 15 },
    asset: 'skins/samurai_poop',
    animationVariant: 'katana',
    vfx: 'slash',
  },
  {
    id: 'knight_poop',
    name: 'Knight Poop',
    description: 'Armor-plated dignity.',
    rarity: 'epic',
    unlock: { type: 'gtp', amount: 480 },
    asset: 'skins/knight_poop',
    animationVariant: 'armor',
    vfx: 'shine',
  },
  {
    id: 'wizard_poop',
    name: 'Wizard Poop',
    description: 'Casts Prestige.',
    rarity: 'epic',
    unlock: { type: 'flush', count: 5 },
    asset: 'skins/wizard_poop',
    animationVariant: 'staff',
    vfx: 'arcane',
  },
  {
    id: 'devil_poop',
    name: 'Devil Poop',
    description: 'Hotter than chili night.',
    rarity: 'epic',
    unlock: { type: 'gtp', amount: 500 },
    asset: 'skins/devil_poop',
    animationVariant: 'horns',
    vfx: 'flame',
  },
  {
    id: 'angel_poop',
    name: 'Angel Poop',
    description: 'Blessed be the fiber.',
    rarity: 'epic',
    unlock: { type: 'gtp', amount: 500 },
    asset: 'skins/angel_poop',
    animationVariant: 'halo',
    vfx: 'light',
  },
  {
    id: 'diamond_poop',
    name: 'Diamond Poop',
    description: 'Pressure makes sparkles.',
    rarity: 'legendary',
    unlock: { type: 'flush', count: 25 },
    asset: 'skins/diamond_poop',
    animationVariant: 'crystal',
    vfx: 'diamond',
  },
  {
    id: 'cyber_poop',
    name: 'Cyber Poop',
    description: 'Jacked into the bowl.',
    rarity: 'legendary',
    unlock: { type: 'gtp', amount: 800 },
    asset: 'skins/cyber_poop',
    animationVariant: 'neon',
    vfx: 'circuit',
  },
  {
    id: 'pixel_poop',
    name: 'Pixel Poop',
    description: '8-bit aroma.',
    rarity: 'legendary',
    unlock: { type: 'achievement', achievementId: 'gens_total_500' },
    asset: 'skins/pixel_poop',
    animationVariant: 'pixel',
    vfx: 'pixel_burst',
  },
  {
    id: 'glitch_poop',
    name: 'Glitch Poop',
    description: 'Rendering... uncertain.',
    rarity: 'legendary',
    unlock: { type: 'gtp', amount: 900 },
    asset: 'skins/glitch_poop',
    animationVariant: 'glitch',
    vfx: 'glitch',
  },
  {
    id: 'nuclear_poop',
    name: 'Nuclear Poop',
    description: 'Handle with tongs.',
    rarity: 'legendary',
    unlock: { type: 'flush', count: 15 },
    asset: 'skins/nuclear_poop',
    animationVariant: 'glow',
    vfx: 'radiation',
  },
  {
    id: 'king_poop',
    name: 'King Poop',
    description: 'Royal flush optional.',
    rarity: 'legendary',
    unlock: { type: 'flush', count: 10 },
    asset: 'skins/king_poop',
    animationVariant: 'crown',
    vfx: 'royalty',
  },
  {
    id: 'black_hole_poop',
    name: 'Black Hole Poop',
    description: 'Absorbs snacks and hope.',
    rarity: 'mythic',
    unlock: { type: 'collection', percent: 50 },
    asset: 'skins/black_hole_poop',
    animationVariant: 'singularity',
    vfx: 'event_horizon',
  },
  {
    id: 'holographic_poop',
    name: 'Holographic Poop',
    description: 'Looks expensive. Is.',
    rarity: 'mythic',
    unlock: { type: 'gtp', amount: 1500 },
    asset: 'skins/holographic_poop',
    animationVariant: 'holo',
    vfx: 'holo',
  },
  {
    id: 'time_traveller_poop',
    name: 'Time Traveller Poop',
    description: 'Already flushed in 3026.',
    rarity: 'mythic',
    unlock: { type: 'world', worldId: 'chrono_chamber' },
    asset: 'skins/time_traveller_poop',
    animationVariant: 'chrono',
    vfx: 'clock',
  },
  {
    id: 'multiverse_poop',
    name: 'Multiverse Poop',
    description: 'Infinite variants, one smell.',
    rarity: 'mythic',
    unlock: { type: 'flush', count: 50 },
    asset: 'skins/multiverse_poop',
    animationVariant: 'split',
    vfx: 'portals',
  },
  {
    id: 'void_poop',
    name: 'Void Poop',
    description: 'There is no wipe in the void.',
    rarity: 'mythic',
    unlock: { type: 'collection', percent: 75 },
    asset: 'skins/void_poop',
    animationVariant: 'void',
    vfx: 'void',
  },
  {
    id: 'developer_poop',
    name: 'Developer Poop',
    description: 'Ships on Friday. Always.',
    rarity: 'mythic',
    unlock: { type: 'achievement', achievementId: 'gens_level_1000' },
    asset: 'skins/developer_poop',
    animationVariant: 'coffee_code',
    vfx: 'terminal',
  },
  {
    id: 'ceo_poop',
    name: 'CEO Poop',
    description: 'Synergizes the swirl.',
    rarity: 'mythic',
    unlock: { type: 'flush', count: 75 },
    asset: 'skins/ceo_poop',
    animationVariant: 'suit',
    vfx: 'money',
  },
  {
    id: '404_poop',
    name: '404 Poop Not Found',
    description: 'Resource missing. Humor found.',
    rarity: 'mythic',
    unlock: { type: 'daily', count: 30 },
    asset: 'skins/404_poop',
    animationVariant: 'error',
    vfx: '404',
  },
  {
    id: 'schrodingers_poop',
    name: "Schrödinger's Poop",
    description: 'Flushed and not flushed.',
    rarity: 'mythic',
    unlock: { type: 'achievement', achievementId: 'flush_50' },
    asset: 'skins/schrodingers_poop',
    animationVariant: 'box',
    vfx: 'quantum',
  },
  {
    id: 'the_final_poop',
    name: 'The Final Poop',
    description: 'Endgame swirl supremacy.',
    rarity: 'mythic',
    unlock: { type: 'flush', count: 100 },
    asset: 'skins/the_final_poop',
    animationVariant: 'final',
    vfx: 'finale',
  },
]

export const SKIN_BY_ID = Object.fromEntries(SKINS.map((s) => [s.id, s]))
