import type { WorldDef } from '../core/types/gameTypes'

export const WORLDS: WorldDef[] = [
  {
    id: 'home_bathroom',
    name: 'Home Bathroom',
    description: 'Where legends begin.',
    unlockFlushCount: 0,
    productionBonus: 0,
    asset: 'worlds/home_bathroom',
  },
  {
    id: 'office_toilet',
    name: 'Office Toilet',
    description: 'Meetings fear this stall.',
    unlockFlushCount: 1,
    productionBonus: 0.05,
    asset: 'worlds/office_toilet',
  },
  {
    id: 'gas_station_restroom',
    name: 'Gas Station Restroom',
    description: 'Brave souls only.',
    unlockFlushCount: 3,
    productionBonus: 0.08,
    asset: 'worlds/gas_station',
  },
  {
    id: 'stadium_loo',
    name: 'Stadium Loo',
    description: 'Halftime heroes.',
    unlockFlushCount: 5,
    productionBonus: 0.1,
    asset: 'worlds/stadium',
  },
  {
    id: 'space_loo',
    name: 'Space Loo',
    description: 'No up, only swirl.',
    unlockFlushCount: 10,
    productionBonus: 0.15,
    asset: 'worlds/space_loo',
  },
  {
    id: 'quantum_bathroom',
    name: 'Quantum Bathroom',
    description: 'Door is both locked and open.',
    unlockFlushCount: 15,
    productionBonus: 0.2,
    asset: 'worlds/quantum_bathroom',
  },
  {
    id: 'chrono_chamber',
    name: 'Chrono Chamber',
    description: 'Flush across timelines.',
    unlockFlushCount: 25,
    productionBonus: 0.25,
    asset: 'worlds/chrono_chamber',
  },
  {
    id: 'neon_arcade_stall',
    name: 'Neon Arcade Stall',
    description: 'Insert coin to sit.',
    unlockFlushCount: 35,
    productionBonus: 0.3,
    asset: 'worlds/neon_arcade',
  },
  {
    id: 'volcanic_spa_toilet',
    name: 'Volcanic Spa Toilet',
    description: 'Relax. Magma optional.',
    unlockFlushCount: 50,
    productionBonus: 0.35,
    asset: 'worlds/volcanic_spa',
  },
  {
    id: 'cloud_restroom',
    name: 'Cloud Restroom',
    description: 'Service unavailable. Soft landing.',
    unlockFlushCount: 65,
    productionBonus: 0.4,
    asset: 'worlds/cloud_restroom',
  },
  {
    id: 'void_washroom',
    name: 'Void Washroom',
    description: 'Echoes sell merchandise.',
    unlockFlushCount: 80,
    productionBonus: 0.5,
    asset: 'worlds/void_washroom',
  },
  {
    id: 'omni_throne',
    name: 'Omni Throne',
    description: 'The seat at the end of plumbing.',
    unlockFlushCount: 100,
    productionBonus: 0.75,
    asset: 'worlds/omni_throne',
  },
]

export const WORLD_BY_ID = Object.fromEntries(WORLDS.map((w) => [w.id, w]))
